# Generated by Django 4.2 on 2023-04-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='L'),
        ),
    ]
